### ISSUE TITLE
Question about data source

### ISSUE THREAD

**Issue by Chandler-Zhu** [wobsoriano/vue-cart#1]
I saw this block of code in `src\store\products.ts`
![image](https://user-images.githubusercontent.com/61914365/136687057-f505cb40-e257-4335-99b2-bde1f801f3e7.png)
My question is where does this fake api lives and how can I add or remove products?
Thanks

**Comment by wobsoriano** [comment]
https://fakestoreapi.com/ 
https://github.com/keikaavousi/fake-store-api
