### ISSUE TITLE
Adding 'sort by ' feature

### ISSUE THREAD

**Issue by Chandler-Zhu** [wobsoriano/vue-cart#2]
I tried to add a 'sort by ' feature in `Home.vue` file, but it didn't work. When I click any of the buttons the order stays the same.
Here is the code
![image](https://user-images.githubusercontent.com/61914365/137442216-64deb518-a805-46c2-af84-66c889247d69.png)

**Comment by wobsoriano** [comment]
Your order variable should be a ref

**Comment by Chandler-Zhu** [comment]
I wrapped order in a `ref` , but now I have another problem: all the buttons work when I click them for the first time, after that they just don't do anything
![image](https://user-images.githubusercontent.com/61914365/137452879-b00cf85f-704b-4e1a-971a-cb36437b1a1a.png)

**Comment by wobsoriano** [comment]
You could lessen your code by adding another computed property and a single function that updates the order ref

```html
<template>
    <ProductCard
     v-for="product in filteredProducts"
     :key="product.id"
     :product="product"
    />
</template>

<script setup lang="ts">
type Order = 'default' | 'priceAsc' | 'priceDesc'

const order = ref<Order>('default')

const filteredProducts = computed(() => {
    if (order.value === 'priceAsc') {
        return productsPL.value
    } else if (order.value === 'priceDesc') {
        return productsPH.value
    }

    return products.value
})

const setOrder = (value: Order) => {
    order.value = value
}
</script>
```

**Comment by Chandler-Zhu** [comment]
I clean up the code a bit but the problem remains, after the first click the buttons stop working
![image](https://user-images.githubusercontent.com/61914365/137470214-c5910715-6dc7-4a58-8470-0644f04b95e0.png)

**Comment by wobsoriano** [comment]
use https://codesandbox.io/ please

**Comment by Chandler-Zhu** [comment]
Here it is
https://codesandbox.io/s/keen-leavitt-yk4qx?file=/src/pages/Home.vue
I notice something funny, when I go to 'Cart' page then go back to Home page, the buttons start working again, but still only for once

**Comment by wobsoriano** [comment]
The problem is that the `.sort` method mutates the original array.

https://codesandbox.io/s/pinia-cart-repro-kw5lk?file=/src/pages/Home.vue

**Comment by Chandler-Zhu** [comment]
One more question: why is it `[...products.value]` instead of `[...products]` ? To me it seems like products is a `ref`

**Comment by wobsoriano** [comment]
yeah products is a ref that's why you need `.value` to access its value :)
