### ISSUE TITLE
npm error :  'Product' only refers to a type, but is being used as a value here

### ISSUE THREAD

**Issue by Chandler-Zhu** [wobsoriano/vue-cart#3]
when I tried to run `npm run build` command, it gives me this error and can't finish building
https://codesandbox.io/s/pinia-cart-repro-kw5lk?file=/src/pages/Home.vue
![image](https://user-images.githubusercontent.com/61914365/137559690-6ad289e1-808b-4937-b5e5-3d8dea9a0258.png)

**Comment by wobsoriano** [comment]
```ts
import { useProductStore } from "../store/products";
import type { Product } from "../store/products";
```

**Comment by Chandler-Zhu** [comment]
In products.ts `Product` is declared as an interface, why is it being imported as a type ? Although it does solve my problem
![image](https://user-images.githubusercontent.com/61914365/137574518-d9adbf2f-4c72-46c7-b86b-aa4771dd1c09.png)
